### ISSUE TITLE
Creating new Website

### ISSUE THREAD

**Issue by DevonDF** [ENG1-Randomly-Generated/Assessment-2#1]
The submitted URL should now link to:
a) all the project-related Assessment 2 deliverables, as well as the Assessment 1
versions (please note the specific requirements for updates, below);
b) the executable for the game;
c) the user manual (including editable source as well as e.g., a pdf manual).

At the moment, because no deliverables have been complete, leave all the links blank - but we need a template setup for the above schema ^.

**Comment by cz1114** [comment]
got it

**Comment by DevonDF** [comment]
Done
